// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BreathNDrinkAPI.Models
{
    public partial class Drinkers
    {
        public Drinkers()
        {
            Promille = new HashSet<Promille>();
            Ratings = new HashSet<Ratings>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public double? MaxPromille { get; set; }

        public virtual ICollection<Promille> Promille { get; set; }
        public virtual ICollection<Ratings> Ratings { get; set; }
    }
}