// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace BreathNDrinkAPI.Models
{
    public partial class FavoriteDrinks
    {
        public int FavoriteId { get; set; }
        public int DrinkerId { get; set; }
        public int DrinkId { get; set; }

        public virtual Drinkers Drinker { get; set; }
    }
}